# Generated by Django 3.2.8 on 2021-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='available_Time',
            field=models.CharField(choices=[('Any Time', 'Any Time'), ('12 am - 6 am', '12 am - 6 am'), ('6 am - 12 pm', '6 am - 12 pm'), ('12 pm - 6 pm', '12 pm - 6 pm'), ('6 pm - 12 am', '6 pm - 12 am')], max_length=15),
        ),
    ]
