# Generated by Django 3.2.8 on 2021-10-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='article_img')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('section', models.CharField(choices=[('Energy', 'Energy'), ('Biomedical', 'Biomedical'), ('Nanotechnology', 'Nanotechnology'), ('Computer Science', 'Computer Science')], max_length=50)),
                ('at_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
