# Generated by Django 3.2.8 on 2021-10-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('Energy', 'Energy'), ('Biomedical', 'Biomedical'), ('Nanotechnology', 'Nanotechnology'), ('Computer Science', 'Computer Science')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='article_info',
            name='section',
        ),
        migrations.AddField(
            model_name='article_info',
            name='type_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.section'),
            preserve_default=False,
        ),
    ]
