# Generated by Django 3.2.8 on 2021-10-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20211022_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_info',
            name='at_time',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
    ]
