# Generated by Django 3.2.8 on 2021-10-23 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_info_at_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_info',
            name='at_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
