# Generated by Django 3.2.8 on 2021-10-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_info_at_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_info',
            options={'verbose_name': ' Information Of Article PLZ '},
        ),
        migrations.AddField(
            model_name='article_info',
            name='small_description',
            field=models.CharField(default=1, max_length=150, verbose_name='Description (max letters "100" )'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article_info',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
