# Generated by Django 3.2.8 on 2021-10-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20211023_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_info',
            name='important_qouts',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
