# Generated by Django 3.2.8 on 2021-10-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_info_important_qouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_info',
            name='paragraph1',
            field=models.TextField(default=1, max_length=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_info',
            name='paragraph2',
            field=models.TextField(default=1, max_length=50000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article_info',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='article_info',
            name='paragraph4',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
