# Generated by Django 3.2.8 on 2021-10-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20211023_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_info',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
