# Generated by Django 3.2.8 on 2021-10-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_article_info_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_info',
            options={'verbose_name': ' Add Article'},
        ),
    ]
