# Generated by Django 3.2.8 on 2021-10-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_article_info_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_info',
            name='small_description',
            field=models.CharField(max_length=150, verbose_name='Description'),
        ),
    ]
