# Generated by Django 3.2.8 on 2021-10-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_article_info_small_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=50),
        ),
    ]
