# Generated by Django 3.2.8 on 2021-10-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_section_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_info',
            options={'ordering': ['title'], 'verbose_name': ' Add Article'},
        ),
    ]
