# Generated by Django 3.2.8 on 2021-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_members',
            name='age',
        ),
        migrations.AddField(
            model_name='team_members',
            name='section',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
