# Generated by Django 3.2.8 on 2021-10-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211016_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='name2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
