# Generated by Django 3.2.8 on 2021-10-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Section Name'),
        ),
    ]
