# Generated by Django 3.2.8 on 2021-10-24 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_sections_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_members',
            options={'ordering': ['name'], 'verbose_name': ' Add Member'},
        ),
    ]
