# Generated by Django 3.2.8 on 2021-10-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_team_members_name2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_members',
            options={'verbose_name': ' Add Member'},
        ),
    ]
