# Generated by Django 3.2.8 on 2021-10-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('educational_level', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('HeadWord', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
