# Generated by Django 3.2.8 on 2021-10-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='The_Goal_Of_Scientific_Research_2',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='The_Goal_Of_Scientific_Research_3',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
