# Generated by Django 3.2.8 on 2021-10-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20211016_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='The_Goal_Of_Scientific_Research_10',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='The_Goal_Of_Scientific_Research_4',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='The_Goal_Of_Scientific_Research_5',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='The_Goal_Of_Scientific_Research_6',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='The_Goal_Of_Scientific_Research_7',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='The_Goal_Of_Scientific_Research_8',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='The_Goal_Of_Scientific_Research_9',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
