# Generated by Django 3.2.8 on 2021-10-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20211016_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='head',
            options={'verbose_name': ' Head Information'},
        ),
    ]
