# Generated by Django 3.2.8 on 2021-10-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_head_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': ' URI Information'},
        ),
    ]
